// Auto-generated. Do not edit!

// (in-package base_nav.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DockFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.distance_to_goal = null;
      this.action_start = null;
    }
    else {
      if (initObj.hasOwnProperty('distance_to_goal')) {
        this.distance_to_goal = initObj.distance_to_goal
      }
      else {
        this.distance_to_goal = 0.0;
      }
      if (initObj.hasOwnProperty('action_start')) {
        this.action_start = initObj.action_start
      }
      else {
        this.action_start = {secs: 0, nsecs: 0};
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DockFeedback
    // Serialize message field [distance_to_goal]
    bufferOffset = _serializer.float32(obj.distance_to_goal, buffer, bufferOffset);
    // Serialize message field [action_start]
    bufferOffset = _serializer.time(obj.action_start, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DockFeedback
    let len;
    let data = new DockFeedback(null);
    // Deserialize message field [distance_to_goal]
    data.distance_to_goal = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [action_start]
    data.action_start = _deserializer.time(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'base_nav/DockFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '203c654257d282adb730530aca547122';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float32 distance_to_goal
    time action_start
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DockFeedback(null);
    if (msg.distance_to_goal !== undefined) {
      resolved.distance_to_goal = msg.distance_to_goal;
    }
    else {
      resolved.distance_to_goal = 0.0
    }

    if (msg.action_start !== undefined) {
      resolved.action_start = msg.action_start;
    }
    else {
      resolved.action_start = {secs: 0, nsecs: 0}
    }

    return resolved;
    }
};

module.exports = DockFeedback;
