// Auto-generated. Do not edit!

// (in-package base_nav.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DockResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.error_code = null;
      this.action_end = null;
    }
    else {
      if (initObj.hasOwnProperty('error_code')) {
        this.error_code = initObj.error_code
      }
      else {
        this.error_code = 0;
      }
      if (initObj.hasOwnProperty('action_end')) {
        this.action_end = initObj.action_end
      }
      else {
        this.action_end = {secs: 0, nsecs: 0};
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DockResult
    // Serialize message field [error_code]
    bufferOffset = _serializer.int32(obj.error_code, buffer, bufferOffset);
    // Serialize message field [action_end]
    bufferOffset = _serializer.time(obj.action_end, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DockResult
    let len;
    let data = new DockResult(null);
    // Deserialize message field [error_code]
    data.error_code = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [action_end]
    data.action_end = _deserializer.time(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'base_nav/DockResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'cc1f185eecc72325073f858a16abb3f3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 SUCCESS = 0
    int32 NO_MAP_TO_FOOTPRINT_TRANSFORM = -1
    int32 PREEMPTED = -2
    
    
    int32 error_code
    time action_end
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DockResult(null);
    if (msg.error_code !== undefined) {
      resolved.error_code = msg.error_code;
    }
    else {
      resolved.error_code = 0
    }

    if (msg.action_end !== undefined) {
      resolved.action_end = msg.action_end;
    }
    else {
      resolved.action_end = {secs: 0, nsecs: 0}
    }

    return resolved;
    }
};

// Constants for message
DockResult.Constants = {
  SUCCESS: 0,
  NO_MAP_TO_FOOTPRINT_TRANSFORM: -1,
  PREEMPTED: -2,
}

module.exports = DockResult;
