// Generated by gencpp from file base_nav/DockGoal.msg
// DO NOT EDIT!


#ifndef BASE_NAV_MESSAGE_DOCKGOAL_H
#define BASE_NAV_MESSAGE_DOCKGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace base_nav
{
template <class ContainerAllocator>
struct DockGoal_
{
  typedef DockGoal_<ContainerAllocator> Type;

  DockGoal_()
    : targetPose()  {
    }
  DockGoal_(const ContainerAllocator& _alloc)
    : targetPose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _targetPose_type;
  _targetPose_type targetPose;





  typedef boost::shared_ptr< ::base_nav::DockGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_nav::DockGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DockGoal_

typedef ::base_nav::DockGoal_<std::allocator<void> > DockGoal;

typedef boost::shared_ptr< ::base_nav::DockGoal > DockGoalPtr;
typedef boost::shared_ptr< ::base_nav::DockGoal const> DockGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_nav::DockGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_nav::DockGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::base_nav::DockGoal_<ContainerAllocator1> & lhs, const ::base_nav::DockGoal_<ContainerAllocator2> & rhs)
{
  return lhs.targetPose == rhs.targetPose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::base_nav::DockGoal_<ContainerAllocator1> & lhs, const ::base_nav::DockGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace base_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::base_nav::DockGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_nav::DockGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_nav::DockGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_nav::DockGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_nav::DockGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_nav::DockGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_nav::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b184098acb98f59165420ef057956537";
  }

  static const char* value(const ::base_nav::DockGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb184098acb98f591ULL;
  static const uint64_t static_value2 = 0x65420ef057956537ULL;
};

template<class ContainerAllocator>
struct DataType< ::base_nav::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_nav/DockGoal";
  }

  static const char* value(const ::base_nav::DockGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_nav::DockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"geometry_msgs/PoseStamped targetPose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::base_nav::DockGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_nav::DockGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.targetPose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_nav::DockGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_nav::DockGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "targetPose: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.targetPose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_NAV_MESSAGE_DOCKGOAL_H
