// Generated by gencpp from file base_nav/DockFeedback.msg
// DO NOT EDIT!


#ifndef BASE_NAV_MESSAGE_DOCKFEEDBACK_H
#define BASE_NAV_MESSAGE_DOCKFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace base_nav
{
template <class ContainerAllocator>
struct DockFeedback_
{
  typedef DockFeedback_<ContainerAllocator> Type;

  DockFeedback_()
    : distance_to_goal(0.0)
    , action_start()  {
    }
  DockFeedback_(const ContainerAllocator& _alloc)
    : distance_to_goal(0.0)
    , action_start()  {
  (void)_alloc;
    }



   typedef float _distance_to_goal_type;
  _distance_to_goal_type distance_to_goal;

   typedef ros::Time _action_start_type;
  _action_start_type action_start;





  typedef boost::shared_ptr< ::base_nav::DockFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_nav::DockFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DockFeedback_

typedef ::base_nav::DockFeedback_<std::allocator<void> > DockFeedback;

typedef boost::shared_ptr< ::base_nav::DockFeedback > DockFeedbackPtr;
typedef boost::shared_ptr< ::base_nav::DockFeedback const> DockFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_nav::DockFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_nav::DockFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::base_nav::DockFeedback_<ContainerAllocator1> & lhs, const ::base_nav::DockFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.distance_to_goal == rhs.distance_to_goal &&
    lhs.action_start == rhs.action_start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::base_nav::DockFeedback_<ContainerAllocator1> & lhs, const ::base_nav::DockFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace base_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::base_nav::DockFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_nav::DockFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_nav::DockFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_nav::DockFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_nav::DockFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_nav::DockFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_nav::DockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "203c654257d282adb730530aca547122";
  }

  static const char* value(const ::base_nav::DockFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x203c654257d282adULL;
  static const uint64_t static_value2 = 0xb730530aca547122ULL;
};

template<class ContainerAllocator>
struct DataType< ::base_nav::DockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_nav/DockFeedback";
  }

  static const char* value(const ::base_nav::DockFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_nav::DockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 distance_to_goal\n"
"time action_start\n"
;
  }

  static const char* value(const ::base_nav::DockFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_nav::DockFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance_to_goal);
      stream.next(m.action_start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DockFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_nav::DockFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_nav::DockFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "distance_to_goal: ";
    Printer<float>::stream(s, indent + "  ", v.distance_to_goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_start: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.action_start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_NAV_MESSAGE_DOCKFEEDBACK_H
