publish_frequency: 5.0
update_frequency: 10.0
global_frame: map
robot_base_frame: base_link
rolling_window: false
robot_radius: 0.3
plugins:
  - {name: static_map, type: "costmap_2d::StaticLayer"}
  - {name: inflater, type: "costmap_2d::InflationLayer"}
  - {name: human_layer_static, type: "cohan_layers::StaticAgentLayer"}
  - {name: human_layer_visible, type: "cohan_layers::AgentVisibilityLayer"}

inflater:
  inflation_radius: 0.2
static_map:
  enabled:              true
  map_topic:            "/map"
human_layer_static:
  robot_radius: 0.46
  agent_radius: 0.31
