# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from base_nav/DockFeedback.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class DockFeedback(genpy.Message):
  _md5sum = "203c654257d282adb730530aca547122"
  _type = "base_nav/DockFeedback"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
float32 distance_to_goal
time action_start
"""
  __slots__ = ['distance_to_goal','action_start']
  _slot_types = ['float32','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       distance_to_goal,action_start

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DockFeedback, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.distance_to_goal is None:
        self.distance_to_goal = 0.
      if self.action_start is None:
        self.action_start = genpy.Time()
    else:
      self.distance_to_goal = 0.
      self.action_start = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_f2I().pack(_x.distance_to_goal, _x.action_start.secs, _x.action_start.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.action_start is None:
        self.action_start = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.distance_to_goal, _x.action_start.secs, _x.action_start.nsecs,) = _get_struct_f2I().unpack(str[start:end])
      self.action_start.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_f2I().pack(_x.distance_to_goal, _x.action_start.secs, _x.action_start.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.action_start is None:
        self.action_start = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.distance_to_goal, _x.action_start.secs, _x.action_start.nsecs,) = _get_struct_f2I().unpack(str[start:end])
      self.action_start.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f2I = None
def _get_struct_f2I():
    global _struct_f2I
    if _struct_f2I is None:
        _struct_f2I = struct.Struct("<f2I")
    return _struct_f2I
