# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from base_nav/DockResult.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class DockResult(genpy.Message):
  _md5sum = "cc1f185eecc72325073f858a16abb3f3"
  _type = "base_nav/DockResult"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
int32 SUCCESS = 0
int32 NO_MAP_TO_FOOTPRINT_TRANSFORM = -1
int32 PREEMPTED = -2


int32 error_code
time action_end
"""
  # Pseudo-constants
  SUCCESS = 0
  NO_MAP_TO_FOOTPRINT_TRANSFORM = -1
  PREEMPTED = -2

  __slots__ = ['error_code','action_end']
  _slot_types = ['int32','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       error_code,action_end

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DockResult, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.error_code is None:
        self.error_code = 0
      if self.action_end is None:
        self.action_end = genpy.Time()
    else:
      self.error_code = 0
      self.action_end = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i2I().pack(_x.error_code, _x.action_end.secs, _x.action_end.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.action_end is None:
        self.action_end = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.error_code, _x.action_end.secs, _x.action_end.nsecs,) = _get_struct_i2I().unpack(str[start:end])
      self.action_end.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i2I().pack(_x.error_code, _x.action_end.secs, _x.action_end.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.action_end is None:
        self.action_end = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.error_code, _x.action_end.secs, _x.action_end.nsecs,) = _get_struct_i2I().unpack(str[start:end])
      self.action_end.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2I = None
def _get_struct_i2I():
    global _struct_i2I
    if _struct_i2I is None:
        _struct_i2I = struct.Struct("<i2I")
    return _struct_i2I
