// Generated by gencpp from file pr2_gazebo_plugins/SetModelsJointsStatesResponse.msg
// DO NOT EDIT!


#ifndef PR2_GAZEBO_PLUGINS_MESSAGE_SETMODELSJOINTSSTATESRESPONSE_H
#define PR2_GAZEBO_PLUGINS_MESSAGE_SETMODELSJOINTSSTATESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pr2_gazebo_plugins
{
template <class ContainerAllocator>
struct SetModelsJointsStatesResponse_
{
  typedef SetModelsJointsStatesResponse_<ContainerAllocator> Type;

  SetModelsJointsStatesResponse_()
    : success(false)
    , status_message()  {
    }
  SetModelsJointsStatesResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , status_message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_message_type;
  _status_message_type status_message;





  typedef boost::shared_ptr< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetModelsJointsStatesResponse_

typedef ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<std::allocator<void> > SetModelsJointsStatesResponse;

typedef boost::shared_ptr< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse > SetModelsJointsStatesResponsePtr;
typedef boost::shared_ptr< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse const> SetModelsJointsStatesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator1> & lhs, const ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.status_message == rhs.status_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator1> & lhs, const ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pr2_gazebo_plugins

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ec6f3eff0161f4257b808b12bc830c2";
  }

  static const char* value(const ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ec6f3eff0161f42ULL;
  static const uint64_t static_value2 = 0x57b808b12bc830c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr2_gazebo_plugins/SetModelsJointsStatesResponse";
  }

  static const char* value(const ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success                                              # return true if spawn successful\n"
"string status_message                                     # comments if available\n"
"\n"
;
  }

  static const char* value(const ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.status_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetModelsJointsStatesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr2_gazebo_plugins::SetModelsJointsStatesResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR2_GAZEBO_PLUGINS_MESSAGE_SETMODELSJOINTSSTATESRESPONSE_H
