// Generated by gencpp from file cohan_msgs/AgentTrajectory.msg
// DO NOT EDIT!


#ifndef COHAN_MSGS_MESSAGE_AGENTTRAJECTORY_H
#define COHAN_MSGS_MESSAGE_AGENTTRAJECTORY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cohan_msgs/Trajectory.h>

namespace cohan_msgs
{
template <class ContainerAllocator>
struct AgentTrajectory_
{
  typedef AgentTrajectory_<ContainerAllocator> Type;

  AgentTrajectory_()
    : header()
    , id(0)
    , type(0)
    , trajectory()  {
    }
  AgentTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , type(0)
    , trajectory(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _id_type;
  _id_type id;

   typedef int8_t _type_type;
  _type_type type;

   typedef  ::cohan_msgs::Trajectory_<ContainerAllocator>  _trajectory_type;
  _trajectory_type trajectory;





  typedef boost::shared_ptr< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct AgentTrajectory_

typedef ::cohan_msgs::AgentTrajectory_<std::allocator<void> > AgentTrajectory;

typedef boost::shared_ptr< ::cohan_msgs::AgentTrajectory > AgentTrajectoryPtr;
typedef boost::shared_ptr< ::cohan_msgs::AgentTrajectory const> AgentTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cohan_msgs::AgentTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cohan_msgs::AgentTrajectory_<ContainerAllocator1> & lhs, const ::cohan_msgs::AgentTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.type == rhs.type &&
    lhs.trajectory == rhs.trajectory;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cohan_msgs::AgentTrajectory_<ContainerAllocator1> & lhs, const ::cohan_msgs::AgentTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cohan_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7853675d8929fd833768dcfd8f02698";
  }

  static const char* value(const ::cohan_msgs::AgentTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7853675d8929fd8ULL;
  static const uint64_t static_value2 = 0x33768dcfd8f02698ULL;
};

template<class ContainerAllocator>
struct DataType< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cohan_msgs/AgentTrajectory";
  }

  static const char* value(const ::cohan_msgs::AgentTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header         header\n"
"uint64                  id\n"
"int8                    type\n"
"cohan_msgs/Trajectory    trajectory\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: cohan_msgs/Trajectory\n"
"std_msgs/Header                  header\n"
"cohan_msgs/TrajectoryPoint[]     points\n"
"\n"
"================================================================================\n"
"MSG: cohan_msgs/TrajectoryPoint\n"
"geometry_msgs/Transform     transform\n"
"geometry_msgs/Twist         velocity\n"
"geometry_msgs/Twist         acceleration\n"
"duration                    time_from_start\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3 linear\n"
"Vector3 angular\n"
;
  }

  static const char* value(const ::cohan_msgs::AgentTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.trajectory);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AgentTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cohan_msgs::AgentTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cohan_msgs::AgentTrajectory_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trajectory: ";
    Printer< ::cohan_msgs::Trajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.trajectory);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COHAN_MSGS_MESSAGE_AGENTTRAJECTORY_H
