// Generated by gencpp from file cohan_msgs/AgentMarkerStamped.msg
// DO NOT EDIT!


#ifndef COHAN_MSGS_MESSAGE_AGENTMARKERSTAMPED_H
#define COHAN_MSGS_MESSAGE_AGENTMARKERSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cohan_msgs/AgentMarker.h>

namespace cohan_msgs
{
template <class ContainerAllocator>
struct AgentMarkerStamped_
{
  typedef AgentMarkerStamped_<ContainerAllocator> Type;

  AgentMarkerStamped_()
    : header()
    , agent()  {
    }
  AgentMarkerStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , agent(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::cohan_msgs::AgentMarker_<ContainerAllocator>  _agent_type;
  _agent_type agent;





  typedef boost::shared_ptr< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> const> ConstPtr;

}; // struct AgentMarkerStamped_

typedef ::cohan_msgs::AgentMarkerStamped_<std::allocator<void> > AgentMarkerStamped;

typedef boost::shared_ptr< ::cohan_msgs::AgentMarkerStamped > AgentMarkerStampedPtr;
typedef boost::shared_ptr< ::cohan_msgs::AgentMarkerStamped const> AgentMarkerStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator1> & lhs, const ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.agent == rhs.agent;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator1> & lhs, const ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cohan_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0285b2aa7ba6b65347e0ed226637a9ff";
  }

  static const char* value(const ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0285b2aa7ba6b653ULL;
  static const uint64_t static_value2 = 0x47e0ed226637a9ffULL;
};

template<class ContainerAllocator>
struct DataType< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cohan_msgs/AgentMarkerStamped";
  }

  static const char* value(const ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header        header\n"
"cohan_msgs/AgentMarker   agent         \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: cohan_msgs/AgentMarker\n"
"uint64              id\n"
"bool                active\n"
"geometry_msgs/Pose  pose\n"
"geometry_msgs/Twist velocity\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3 linear\n"
"Vector3 angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.agent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AgentMarkerStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cohan_msgs::AgentMarkerStamped_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "agent: ";
    Printer< ::cohan_msgs::AgentMarker_<ContainerAllocator> >::stream(s, indent + "  ", v.agent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COHAN_MSGS_MESSAGE_AGENTMARKERSTAMPED_H
