// Generated by gencpp from file cohan_msgs/TrackedAgents.msg
// DO NOT EDIT!


#ifndef COHAN_MSGS_MESSAGE_TRACKEDAGENTS_H
#define COHAN_MSGS_MESSAGE_TRACKEDAGENTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cohan_msgs/TrackedAgent.h>

namespace cohan_msgs
{
template <class ContainerAllocator>
struct TrackedAgents_
{
  typedef TrackedAgents_<ContainerAllocator> Type;

  TrackedAgents_()
    : header()
    , agents()  {
    }
  TrackedAgents_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , agents(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::cohan_msgs::TrackedAgent_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cohan_msgs::TrackedAgent_<ContainerAllocator> >> _agents_type;
  _agents_type agents;





  typedef boost::shared_ptr< ::cohan_msgs::TrackedAgents_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cohan_msgs::TrackedAgents_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedAgents_

typedef ::cohan_msgs::TrackedAgents_<std::allocator<void> > TrackedAgents;

typedef boost::shared_ptr< ::cohan_msgs::TrackedAgents > TrackedAgentsPtr;
typedef boost::shared_ptr< ::cohan_msgs::TrackedAgents const> TrackedAgentsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cohan_msgs::TrackedAgents_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cohan_msgs::TrackedAgents_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cohan_msgs::TrackedAgents_<ContainerAllocator1> & lhs, const ::cohan_msgs::TrackedAgents_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.agents == rhs.agents;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cohan_msgs::TrackedAgents_<ContainerAllocator1> & lhs, const ::cohan_msgs::TrackedAgents_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cohan_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cohan_msgs::TrackedAgents_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cohan_msgs::TrackedAgents_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohan_msgs::TrackedAgents_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohan_msgs::TrackedAgents_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohan_msgs::TrackedAgents_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohan_msgs::TrackedAgents_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cohan_msgs::TrackedAgents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc1cf2007c31152542d2c6c79f8fd329";
  }

  static const char* value(const ::cohan_msgs::TrackedAgents_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc1cf2007c311525ULL;
  static const uint64_t static_value2 = 0x42d2c6c79f8fd329ULL;
};

template<class ContainerAllocator>
struct DataType< ::cohan_msgs::TrackedAgents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cohan_msgs/TrackedAgents";
  }

  static const char* value(const ::cohan_msgs::TrackedAgents_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cohan_msgs::TrackedAgents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header                         header\n"
"cohan_msgs/TrackedAgent[]      agents\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: cohan_msgs/TrackedAgent\n"
"# states\n"
"int8 STATIC=0\n"
"int8 MOVING=1\n"
"int8 STOPPED=2\n"
"int8 BLOCKED=3\n"
"\n"
"uint64              track_id\n"
"int8                state\n"
"int8                type\n"
"string              name\n"
"TrackedSegment[]    segments\n"
"\n"
"================================================================================\n"
"MSG: cohan_msgs/TrackedSegment\n"
"int8                                type\n"
"geometry_msgs/PoseWithCovariance    pose\n"
"geometry_msgs/TwistWithCovariance   twist\n"
"geometry_msgs/AccelWithCovariance   accel\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3 linear\n"
"Vector3 angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/AccelWithCovariance\n"
"# This expresses acceleration in free space with uncertainty.\n"
"\n"
"Accel accel\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Accel\n"
"# This expresses acceleration in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
;
  }

  static const char* value(const ::cohan_msgs::TrackedAgents_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cohan_msgs::TrackedAgents_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.agents);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedAgents_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cohan_msgs::TrackedAgents_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cohan_msgs::TrackedAgents_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "agents: ";
    if (v.agents.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.agents.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::cohan_msgs::TrackedAgent_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.agents[i]);
    }
    if (v.agents.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // COHAN_MSGS_MESSAGE_TRACKEDAGENTS_H
