//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AgentPathPrediction
{
    [Serializable]
    public class AgentPoseMsg : Message
    {
        public const string k_RosMessageName = "agent_path_prediction/AgentPose";
        public override string RosMessageName => k_RosMessageName;

        public sbyte type;
        public long id;
        public Geometry.PoseStampedMsg pose;

        public AgentPoseMsg()
        {
            this.type = 0;
            this.id = 0;
            this.pose = new Geometry.PoseStampedMsg();
        }

        public AgentPoseMsg(sbyte type, long id, Geometry.PoseStampedMsg pose)
        {
            this.type = type;
            this.id = id;
            this.pose = pose;
        }

        public static AgentPoseMsg Deserialize(MessageDeserializer deserializer) => new AgentPoseMsg(deserializer);

        private AgentPoseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
            deserializer.Read(out this.id);
            this.pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
            serializer.Write(this.id);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "AgentPoseMsg: " +
            "\ntype: " + type.ToString() +
            "\nid: " + id.ToString() +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
