//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AgentPathPrediction
{
    [Serializable]
    public class PredictedGoalMsg : Message
    {
        public const string k_RosMessageName = "agent_path_prediction/PredictedGoal";
        public override string RosMessageName => k_RosMessageName;

        public bool changed;
        public Geometry.PoseStampedMsg goal;

        public PredictedGoalMsg()
        {
            this.changed = false;
            this.goal = new Geometry.PoseStampedMsg();
        }

        public PredictedGoalMsg(bool changed, Geometry.PoseStampedMsg goal)
        {
            this.changed = changed;
            this.goal = goal;
        }

        public static PredictedGoalMsg Deserialize(MessageDeserializer deserializer) => new PredictedGoalMsg(deserializer);

        private PredictedGoalMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.changed);
            this.goal = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.changed);
            serializer.Write(this.goal);
        }

        public override string ToString()
        {
            return "PredictedGoalMsg: " +
            "\nchanged: " + changed.ToString() +
            "\ngoal: " + goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
