// Generated by gencpp from file cohan_msgs/AgentTimeToGoal.msg
// DO NOT EDIT!


#ifndef COHAN_MSGS_MESSAGE_AGENTTIMETOGOAL_H
#define COHAN_MSGS_MESSAGE_AGENTTIMETOGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cohan_msgs
{
template <class ContainerAllocator>
struct AgentTimeToGoal_
{
  typedef AgentTimeToGoal_<ContainerAllocator> Type;

  AgentTimeToGoal_()
    : header()
    , id(0)
    , type(0)
    , time_to_goal()  {
    }
  AgentTimeToGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , type(0)
    , time_to_goal()  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _id_type;
  _id_type id;

   typedef int8_t _type_type;
  _type_type type;

   typedef ros::Duration _time_to_goal_type;
  _time_to_goal_type time_to_goal;





  typedef boost::shared_ptr< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> const> ConstPtr;

}; // struct AgentTimeToGoal_

typedef ::cohan_msgs::AgentTimeToGoal_<std::allocator<void> > AgentTimeToGoal;

typedef boost::shared_ptr< ::cohan_msgs::AgentTimeToGoal > AgentTimeToGoalPtr;
typedef boost::shared_ptr< ::cohan_msgs::AgentTimeToGoal const> AgentTimeToGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator1> & lhs, const ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.type == rhs.type &&
    lhs.time_to_goal == rhs.time_to_goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator1> & lhs, const ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cohan_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa9354bd82de41a4f433be8a3687818a";
  }

  static const char* value(const ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa9354bd82de41a4ULL;
  static const uint64_t static_value2 = 0xf433be8a3687818aULL;
};

template<class ContainerAllocator>
struct DataType< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cohan_msgs/AgentTimeToGoal";
  }

  static const char* value(const ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint64          id\n"
"int8            type\n"
"duration        time_to_goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.time_to_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AgentTimeToGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cohan_msgs::AgentTimeToGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "time_to_goal: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.time_to_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COHAN_MSGS_MESSAGE_AGENTTIMETOGOAL_H
