// Generated by gencpp from file cohan_msgs/GetTrajectory.msg
// DO NOT EDIT!


#ifndef COHAN_MSGS_MESSAGE_GETTRAJECTORY_H
#define COHAN_MSGS_MESSAGE_GETTRAJECTORY_H

#include <ros/service_traits.h>


#include <cohan_msgs/GetTrajectoryRequest.h>
#include <cohan_msgs/GetTrajectoryResponse.h>


namespace cohan_msgs
{

struct GetTrajectory
{

typedef GetTrajectoryRequest Request;
typedef GetTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTrajectory
} // namespace cohan_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cohan_msgs::GetTrajectory > {
  static const char* value()
  {
    return "b06ef2124717e19c8dcfad526f6c1f42";
  }

  static const char* value(const ::cohan_msgs::GetTrajectory&) { return value(); }
};

template<>
struct DataType< ::cohan_msgs::GetTrajectory > {
  static const char* value()
  {
    return "cohan_msgs/GetTrajectory";
  }

  static const char* value(const ::cohan_msgs::GetTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::cohan_msgs::GetTrajectoryRequest> should match
// service_traits::MD5Sum< ::cohan_msgs::GetTrajectory >
template<>
struct MD5Sum< ::cohan_msgs::GetTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cohan_msgs::GetTrajectory >::value();
  }
  static const char* value(const ::cohan_msgs::GetTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cohan_msgs::GetTrajectoryRequest> should match
// service_traits::DataType< ::cohan_msgs::GetTrajectory >
template<>
struct DataType< ::cohan_msgs::GetTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::cohan_msgs::GetTrajectory >::value();
  }
  static const char* value(const ::cohan_msgs::GetTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cohan_msgs::GetTrajectoryResponse> should match
// service_traits::MD5Sum< ::cohan_msgs::GetTrajectory >
template<>
struct MD5Sum< ::cohan_msgs::GetTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cohan_msgs::GetTrajectory >::value();
  }
  static const char* value(const ::cohan_msgs::GetTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cohan_msgs::GetTrajectoryResponse> should match
// service_traits::DataType< ::cohan_msgs::GetTrajectory >
template<>
struct DataType< ::cohan_msgs::GetTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::cohan_msgs::GetTrajectory >::value();
  }
  static const char* value(const ::cohan_msgs::GetTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COHAN_MSGS_MESSAGE_GETTRAJECTORY_H
