// Generated by gencpp from file cohan_msgs/Optimize.msg
// DO NOT EDIT!


#ifndef COHAN_MSGS_MESSAGE_OPTIMIZE_H
#define COHAN_MSGS_MESSAGE_OPTIMIZE_H

#include <ros/service_traits.h>


#include <cohan_msgs/OptimizeRequest.h>
#include <cohan_msgs/OptimizeResponse.h>


namespace cohan_msgs
{

struct Optimize
{

typedef OptimizeRequest Request;
typedef OptimizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Optimize
} // namespace cohan_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cohan_msgs::Optimize > {
  static const char* value()
  {
    return "268314f168a8e54386e219ff71892d27";
  }

  static const char* value(const ::cohan_msgs::Optimize&) { return value(); }
};

template<>
struct DataType< ::cohan_msgs::Optimize > {
  static const char* value()
  {
    return "cohan_msgs/Optimize";
  }

  static const char* value(const ::cohan_msgs::Optimize&) { return value(); }
};


// service_traits::MD5Sum< ::cohan_msgs::OptimizeRequest> should match
// service_traits::MD5Sum< ::cohan_msgs::Optimize >
template<>
struct MD5Sum< ::cohan_msgs::OptimizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cohan_msgs::Optimize >::value();
  }
  static const char* value(const ::cohan_msgs::OptimizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cohan_msgs::OptimizeRequest> should match
// service_traits::DataType< ::cohan_msgs::Optimize >
template<>
struct DataType< ::cohan_msgs::OptimizeRequest>
{
  static const char* value()
  {
    return DataType< ::cohan_msgs::Optimize >::value();
  }
  static const char* value(const ::cohan_msgs::OptimizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cohan_msgs::OptimizeResponse> should match
// service_traits::MD5Sum< ::cohan_msgs::Optimize >
template<>
struct MD5Sum< ::cohan_msgs::OptimizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cohan_msgs::Optimize >::value();
  }
  static const char* value(const ::cohan_msgs::OptimizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cohan_msgs::OptimizeResponse> should match
// service_traits::DataType< ::cohan_msgs::Optimize >
template<>
struct DataType< ::cohan_msgs::OptimizeResponse>
{
  static const char* value()
  {
    return DataType< ::cohan_msgs::Optimize >::value();
  }
  static const char* value(const ::cohan_msgs::OptimizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COHAN_MSGS_MESSAGE_OPTIMIZE_H
