(cl:defpackage cohan_msgs-srv
  (:use )
  (:export
   "GETTRAJECTORY"
   "<GETTRAJECTORY-REQUEST>"
   "GETTRAJECTORY-REQUEST"
   "<GETTRAJECTORY-RESPONSE>"
   "GETTRAJECTORY-RESPONSE"
   "OPTIMIZE"
   "<OPTIMIZE-REQUEST>"
   "OPTIMIZE-REQUEST"
   "<OPTIMIZE-RESPONSE>"
   "OPTIMIZE-RESPONSE"
  ))

