// Generated by gencpp from file cohan_gazebo/setGoal.msg
// DO NOT EDIT!


#ifndef COHAN_GAZEBO_MESSAGE_SETGOAL_H
#define COHAN_GAZEBO_MESSAGE_SETGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace cohan_gazebo
{
template <class ContainerAllocator>
struct setGoal_
{
  typedef setGoal_<ContainerAllocator> Type;

  setGoal_()
    : id(0)
    , goal()  {
    }
  setGoal_(const ContainerAllocator& _alloc)
    : id(0)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::cohan_gazebo::setGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cohan_gazebo::setGoal_<ContainerAllocator> const> ConstPtr;

}; // struct setGoal_

typedef ::cohan_gazebo::setGoal_<std::allocator<void> > setGoal;

typedef boost::shared_ptr< ::cohan_gazebo::setGoal > setGoalPtr;
typedef boost::shared_ptr< ::cohan_gazebo::setGoal const> setGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cohan_gazebo::setGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cohan_gazebo::setGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cohan_gazebo::setGoal_<ContainerAllocator1> & lhs, const ::cohan_gazebo::setGoal_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cohan_gazebo::setGoal_<ContainerAllocator1> & lhs, const ::cohan_gazebo::setGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cohan_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cohan_gazebo::setGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cohan_gazebo::setGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohan_gazebo::setGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cohan_gazebo::setGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohan_gazebo::setGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cohan_gazebo::setGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cohan_gazebo::setGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37dce9f174cd54246b8b68dda92de7d8";
  }

  static const char* value(const ::cohan_gazebo::setGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37dce9f174cd5424ULL;
  static const uint64_t static_value2 = 0x6b8b68dda92de7d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::cohan_gazebo::setGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cohan_gazebo/setGoal";
  }

  static const char* value(const ::cohan_gazebo::setGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cohan_gazebo::setGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64                     id\n"
"geometry_msgs/PoseStamped goal\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::cohan_gazebo::setGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cohan_gazebo::setGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cohan_gazebo::setGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cohan_gazebo::setGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COHAN_GAZEBO_MESSAGE_SETGOAL_H
