// Generated by gencpp from file hateb_local_planner/Approach.msg
// DO NOT EDIT!


#ifndef HATEB_LOCAL_PLANNER_MESSAGE_APPROACH_H
#define HATEB_LOCAL_PLANNER_MESSAGE_APPROACH_H

#include <ros/service_traits.h>


#include <hateb_local_planner/ApproachRequest.h>
#include <hateb_local_planner/ApproachResponse.h>


namespace hateb_local_planner
{

struct Approach
{

typedef ApproachRequest Request;
typedef ApproachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Approach
} // namespace hateb_local_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hateb_local_planner::Approach > {
  static const char* value()
  {
    return "199a24b4d2ab7be80f7fdf2e5958eec5";
  }

  static const char* value(const ::hateb_local_planner::Approach&) { return value(); }
};

template<>
struct DataType< ::hateb_local_planner::Approach > {
  static const char* value()
  {
    return "hateb_local_planner/Approach";
  }

  static const char* value(const ::hateb_local_planner::Approach&) { return value(); }
};


// service_traits::MD5Sum< ::hateb_local_planner::ApproachRequest> should match
// service_traits::MD5Sum< ::hateb_local_planner::Approach >
template<>
struct MD5Sum< ::hateb_local_planner::ApproachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hateb_local_planner::Approach >::value();
  }
  static const char* value(const ::hateb_local_planner::ApproachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hateb_local_planner::ApproachRequest> should match
// service_traits::DataType< ::hateb_local_planner::Approach >
template<>
struct DataType< ::hateb_local_planner::ApproachRequest>
{
  static const char* value()
  {
    return DataType< ::hateb_local_planner::Approach >::value();
  }
  static const char* value(const ::hateb_local_planner::ApproachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hateb_local_planner::ApproachResponse> should match
// service_traits::MD5Sum< ::hateb_local_planner::Approach >
template<>
struct MD5Sum< ::hateb_local_planner::ApproachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hateb_local_planner::Approach >::value();
  }
  static const char* value(const ::hateb_local_planner::ApproachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hateb_local_planner::ApproachResponse> should match
// service_traits::DataType< ::hateb_local_planner::Approach >
template<>
struct DataType< ::hateb_local_planner::ApproachResponse>
{
  static const char* value()
  {
    return DataType< ::hateb_local_planner::Approach >::value();
  }
  static const char* value(const ::hateb_local_planner::ApproachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HATEB_LOCAL_PLANNER_MESSAGE_APPROACH_H
