// Generated by gencpp from file hateb_local_planner/getOptimVel.msg
// DO NOT EDIT!


#ifndef HATEB_LOCAL_PLANNER_MESSAGE_GETOPTIMVEL_H
#define HATEB_LOCAL_PLANNER_MESSAGE_GETOPTIMVEL_H

#include <ros/service_traits.h>


#include <hateb_local_planner/getOptimVelRequest.h>
#include <hateb_local_planner/getOptimVelResponse.h>


namespace hateb_local_planner
{

struct getOptimVel
{

typedef getOptimVelRequest Request;
typedef getOptimVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getOptimVel
} // namespace hateb_local_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hateb_local_planner::getOptimVel > {
  static const char* value()
  {
    return "9064de66b0c4b1d712622f9ef99fd185";
  }

  static const char* value(const ::hateb_local_planner::getOptimVel&) { return value(); }
};

template<>
struct DataType< ::hateb_local_planner::getOptimVel > {
  static const char* value()
  {
    return "hateb_local_planner/getOptimVel";
  }

  static const char* value(const ::hateb_local_planner::getOptimVel&) { return value(); }
};


// service_traits::MD5Sum< ::hateb_local_planner::getOptimVelRequest> should match
// service_traits::MD5Sum< ::hateb_local_planner::getOptimVel >
template<>
struct MD5Sum< ::hateb_local_planner::getOptimVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hateb_local_planner::getOptimVel >::value();
  }
  static const char* value(const ::hateb_local_planner::getOptimVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hateb_local_planner::getOptimVelRequest> should match
// service_traits::DataType< ::hateb_local_planner::getOptimVel >
template<>
struct DataType< ::hateb_local_planner::getOptimVelRequest>
{
  static const char* value()
  {
    return DataType< ::hateb_local_planner::getOptimVel >::value();
  }
  static const char* value(const ::hateb_local_planner::getOptimVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hateb_local_planner::getOptimVelResponse> should match
// service_traits::MD5Sum< ::hateb_local_planner::getOptimVel >
template<>
struct MD5Sum< ::hateb_local_planner::getOptimVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hateb_local_planner::getOptimVel >::value();
  }
  static const char* value(const ::hateb_local_planner::getOptimVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hateb_local_planner::getOptimVelResponse> should match
// service_traits::DataType< ::hateb_local_planner::getOptimVel >
template<>
struct DataType< ::hateb_local_planner::getOptimVelResponse>
{
  static const char* value()
  {
    return DataType< ::hateb_local_planner::getOptimVel >::value();
  }
  static const char* value(const ::hateb_local_planner::getOptimVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HATEB_LOCAL_PLANNER_MESSAGE_GETOPTIMVEL_H
