// Generated by gencpp from file hateb_local_planner/getPlanningResponse.msg
// DO NOT EDIT!


#ifndef HATEB_LOCAL_PLANNER_MESSAGE_GETPLANNINGRESPONSE_H
#define HATEB_LOCAL_PLANNER_MESSAGE_GETPLANNINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hateb_local_planner
{
template <class ContainerAllocator>
struct getPlanningResponse_
{
  typedef getPlanningResponse_<ContainerAllocator> Type;

  getPlanningResponse_()
    : mode(0)  {
    }
  getPlanningResponse_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef int8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> const> ConstPtr;

}; // struct getPlanningResponse_

typedef ::hateb_local_planner::getPlanningResponse_<std::allocator<void> > getPlanningResponse;

typedef boost::shared_ptr< ::hateb_local_planner::getPlanningResponse > getPlanningResponsePtr;
typedef boost::shared_ptr< ::hateb_local_planner::getPlanningResponse const> getPlanningResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hateb_local_planner::getPlanningResponse_<ContainerAllocator1> & lhs, const ::hateb_local_planner::getPlanningResponse_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hateb_local_planner::getPlanningResponse_<ContainerAllocator1> & lhs, const ::hateb_local_planner::getPlanningResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hateb_local_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "418c02483a8ca57215fb7b31c5c87234";
  }

  static const char* value(const ::hateb_local_planner::getPlanningResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x418c02483a8ca572ULL;
  static const uint64_t static_value2 = 0x15fb7b31c5c87234ULL;
};

template<class ContainerAllocator>
struct DataType< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hateb_local_planner/getPlanningResponse";
  }

  static const char* value(const ::hateb_local_planner::getPlanningResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 mode\n"
"\n"
;
  }

  static const char* value(const ::hateb_local_planner::getPlanningResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct getPlanningResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hateb_local_planner::getPlanningResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hateb_local_planner::getPlanningResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HATEB_LOCAL_PLANNER_MESSAGE_GETPLANNINGRESPONSE_H
