// Generated by gencpp from file hateb_local_planner/getPlanning.msg
// DO NOT EDIT!


#ifndef HATEB_LOCAL_PLANNER_MESSAGE_GETPLANNING_H
#define HATEB_LOCAL_PLANNER_MESSAGE_GETPLANNING_H

#include <ros/service_traits.h>


#include <hateb_local_planner/getPlanningRequest.h>
#include <hateb_local_planner/getPlanningResponse.h>


namespace hateb_local_planner
{

struct getPlanning
{

typedef getPlanningRequest Request;
typedef getPlanningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getPlanning
} // namespace hateb_local_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hateb_local_planner::getPlanning > {
  static const char* value()
  {
    return "418c02483a8ca57215fb7b31c5c87234";
  }

  static const char* value(const ::hateb_local_planner::getPlanning&) { return value(); }
};

template<>
struct DataType< ::hateb_local_planner::getPlanning > {
  static const char* value()
  {
    return "hateb_local_planner/getPlanning";
  }

  static const char* value(const ::hateb_local_planner::getPlanning&) { return value(); }
};


// service_traits::MD5Sum< ::hateb_local_planner::getPlanningRequest> should match
// service_traits::MD5Sum< ::hateb_local_planner::getPlanning >
template<>
struct MD5Sum< ::hateb_local_planner::getPlanningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hateb_local_planner::getPlanning >::value();
  }
  static const char* value(const ::hateb_local_planner::getPlanningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hateb_local_planner::getPlanningRequest> should match
// service_traits::DataType< ::hateb_local_planner::getPlanning >
template<>
struct DataType< ::hateb_local_planner::getPlanningRequest>
{
  static const char* value()
  {
    return DataType< ::hateb_local_planner::getPlanning >::value();
  }
  static const char* value(const ::hateb_local_planner::getPlanningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hateb_local_planner::getPlanningResponse> should match
// service_traits::MD5Sum< ::hateb_local_planner::getPlanning >
template<>
struct MD5Sum< ::hateb_local_planner::getPlanningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hateb_local_planner::getPlanning >::value();
  }
  static const char* value(const ::hateb_local_planner::getPlanningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hateb_local_planner::getPlanningResponse> should match
// service_traits::DataType< ::hateb_local_planner::getPlanning >
template<>
struct DataType< ::hateb_local_planner::getPlanningResponse>
{
  static const char* value()
  {
    return DataType< ::hateb_local_planner::getPlanning >::value();
  }
  static const char* value(const ::hateb_local_planner::getPlanningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HATEB_LOCAL_PLANNER_MESSAGE_GETPLANNING_H
