//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav
{
    [Serializable]
    public class GetMapResultMsg : Message
    {
        public const string k_RosMessageName = "nav_msgs/GetMapResult";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public OccupancyGridMsg map;

        public GetMapResultMsg()
        {
            this.map = new OccupancyGridMsg();
        }

        public GetMapResultMsg(OccupancyGridMsg map)
        {
            this.map = map;
        }

        public static GetMapResultMsg Deserialize(MessageDeserializer deserializer) => new GetMapResultMsg(deserializer);

        private GetMapResultMsg(MessageDeserializer deserializer)
        {
            this.map = OccupancyGridMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.map);
        }

        public override string ToString()
        {
            return "GetMapResultMsg: " +
            "\nmap: " + map.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
