//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav
{
    [Serializable]
    public class GetMapActionMsg : Message
    {
        public const string k_RosMessageName = "nav_msgs/GetMapAction";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public GetMapActionGoalMsg action_goal;
        public GetMapActionResultMsg action_result;
        public GetMapActionFeedbackMsg action_feedback;

        public GetMapActionMsg()
        {
            this.action_goal = new GetMapActionGoalMsg();
            this.action_result = new GetMapActionResultMsg();
            this.action_feedback = new GetMapActionFeedbackMsg();
        }

        public GetMapActionMsg(GetMapActionGoalMsg action_goal, GetMapActionResultMsg action_result, GetMapActionFeedbackMsg action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }

        public static GetMapActionMsg Deserialize(MessageDeserializer deserializer) => new GetMapActionMsg(deserializer);

        private GetMapActionMsg(MessageDeserializer deserializer)
        {
            this.action_goal = GetMapActionGoalMsg.Deserialize(deserializer);
            this.action_result = GetMapActionResultMsg.Deserialize(deserializer);
            this.action_feedback = GetMapActionFeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_goal);
            serializer.Write(this.action_result);
            serializer.Write(this.action_feedback);
        }

        public override string ToString()
        {
            return "GetMapActionMsg: " +
            "\naction_goal: " + action_goal.ToString() +
            "\naction_result: " + action_result.ToString() +
            "\naction_feedback: " + action_feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
