//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Sensor
{
    [Serializable]
    public class CompressedImageMsg : Message
    {
        public const string k_RosMessageName = "sensor_msgs/CompressedImage";
        public override string RosMessageName => k_RosMessageName;

        //  This message contains a compressed image
        public HeaderMsg header;
        //  Header timestamp should be acquisition time of image
        //  Header frame_id should be optical frame of camera
        //  origin of frame should be optical center of camera
        //  +x should point to the right in the image
        //  +y should point down in the image
        //  +z should point into to plane of the image
        public string format;
        //  Specifies the format of the data
        //  Acceptable values differ by the image transport used:
        //  - compressed_image_transport:
        //      ORIG_PIXFMT; CODEC compressed [COMPRESSED_PIXFMT]
        //    where:
        //    - ORIG_PIXFMT is pixel format of the raw image, i.e.
        //      the content of sensor_msgs/Image/encoding with
        //      values from include/sensor_msgs/image_encodings.h
        //    - CODEC is one of [jpeg, png]
        //    - COMPRESSED_PIXFMT is only appended for color images
        //      and is the pixel format used by the compression
        //      algorithm. Valid values for jpeg encoding are:
        //      [bgr8, rgb8]. Valid values for png encoding are:
        //      [bgr8, rgb8, bgr16, rgb16].
        //    If the field is empty or does not correspond to the
        //    above pattern, the image is treated as bgr8 or mono8
        //    jpeg image (depending on the number of channels).
        //  - compressed_depth_image_transport:
        //      ORIG_PIXFMT; compressedDepth CODEC
        //    where:
        //    - ORIG_PIXFMT is pixel format of the raw image, i.e.
        //      the content of sensor_msgs/Image/encoding with
        //      values from include/sensor_msgs/image_encodings.h
        //      It is usually one of [16UC1, 32FC1].
        //    - CODEC is one of [png, rvl]
        //    If the field is empty or does not correspond to the
        //    above pattern, the image is treated as png image.
        //  - Other image transports can store whatever values they
        //    need for successful decoding of the image. Refer to
        //    documentation of the other transports for details.
        public byte[] data;
        //  Compressed image buffer

        public CompressedImageMsg()
        {
            this.header = new HeaderMsg();
            this.format = "";
            this.data = new byte[0];
        }

        public CompressedImageMsg(HeaderMsg header, string format, byte[] data)
        {
            this.header = header;
            this.format = format;
            this.data = data;
        }

        public static CompressedImageMsg Deserialize(MessageDeserializer deserializer) => new CompressedImageMsg(deserializer);

        private CompressedImageMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.format);
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.format);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "CompressedImageMsg: " +
            "\nheader: " + header.ToString() +
            "\nformat: " + format.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
